"""
report_generator.py
--------------------
Generates text and PDF health reports.
"""

import os
from datetime import datetime
from fpdf import FPDF

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_text_report(username, symptoms, disease, confidence, suggestion):
    """Generate a plain-text health report and save it to /reports."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    path = os.path.join(REPORTS_DIR, f"health_report_{username}.txt")

    content = f"""
================================================================
              AI HEALTH SYMPTOM CHECKER - HEALTH REPORT
================================================================
Patient Name      : {username}
Date / Time       : {timestamp}
----------------------------------------------------------------
Symptoms Reported : {', '.join(symptoms) if symptoms else 'None'}
Predicted Disease : {disease}
Confidence Score  : {confidence}%
----------------------------------------------------------------
AI Recommendation :
{suggestion}
----------------------------------------------------------------
Disclaimer: This report is generated by an AI system and is
intended for educational purposes only. Please consult a
qualified healthcare professional for medical advice.
================================================================
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


class PDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(33, 97, 140)
        self.cell(0, 10, "AI Health Symptom Checker - Health Report", ln=True, align="C")
        self.set_draw_color(33, 97, 140)
        self.line(10, 22, 200, 22)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AI Health Symptom Checker", align="C")


def generate_pdf_report(username, symptoms, disease, confidence, suggestion):
    """Generate a professionally formatted PDF health report."""
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(0, 0, 0)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    pdf.cell(0, 8, f"Patient Name : {username}", ln=True)
    pdf.cell(0, 8, f"Date / Time  : {timestamp}", ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Reported Symptoms:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 7, ", ".join(symptoms) if symptoms else "None")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Prediction Result:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 7, f"Predicted Disease : {disease}", ln=True)
    pdf.cell(0, 7, f"Confidence Score  : {confidence}%", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "AI Health Recommendation:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 7, suggestion)
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 6,
        "Disclaimer: This report is generated by an AI system and is intended "
        "for educational purposes only. Please consult a qualified healthcare "
        "professional for medical advice."
    )

    path = os.path.join(REPORTS_DIR, f"health_report_{username}.pdf")
    pdf.output(path)
    return path
